### ISSUE TITLE
Click on the visualization item with no definition behavior 

### ISSUE THREAD

**Issue by roshan-gh** [dash0hq/otelbin#124]
Currently, a normal click on visualization items redirects the cursor to item definitions in the editor. also along with the custom validation errors, the pipeline visualization is functional, what should happen when the user clicks on the pipeline visualization item that still is not defined in the editor's config?

example config:
https://www.otelbin.io/s/d0e264da-9b18-4e37-9fbc-46e12518bf75

<img width="1664" alt="image" src="https://github.com/dash0hq/otelbin/assets/558256/b12dfddf-8f00-48cd-adbd-f6a32321560e">

in this config, "prometheus" is defined as an exporter in pipelines, but there is no definition for it. what should happen when the user clicks on "prometheus" visualization?

**Comment by mmanciop** [comment]
Should go to the dangling reference, in this case, on line 28, and ideally make the error visible (note that in the screenshot the editor is NOT correctly showing that that `prometheus` is dangling, and that smells like a bug)

**Comment by roshan-gh** [comment]
@mmanciop Thank you. The screenshot is from an old version where OTelBin didn't have custom browser-side validation.
