### ISSUE TITLE
Server-side validation - envvar interpolation

### ISSUE THREAD

**Issue by roshan-gh** [dash0hq/otelbin#156]
Support envvar interpolation for the server-side validation

**Comment by roshan-gh** [comment]
@mmanciop opened the issue

**Comment by mmanciop** [comment]
We should detect env vars to be interpolated and ask for test values to be used in the backend validation.

**Comment by mmanciop** [comment]
Based on https://github.com/open-telemetry/opentelemetry-collector/pull/4742, when validating backend-side, in the frontend we need to:

1. Detect `${...}` and `$[a-zA-Z_][a-zA-Z0-9_]*` sequences.

2. Check whether the text wrapped by `${...}` has a `[a-zA-Z_]:` prefix; if so, we treat the `env:` prefix as denoting an environment variable (same as `$[a-zA-Z_][a-zA-Z0-9_]*`). Other prefixes, like `file:`, need to raise an error that disables backend validation, as we won't be able to resolve the values server-side.

Given the list of environment variable names found with the steps above, we need to prompt the user for input before any backend validation can occur. I do not see a meaningful and practical way of proposing default values at this stage.

As a note about other configuration providers (e.g., `file:`): while they will prevent any validation from succeeding, by disabling validation, we are giving up on catch other errors _before_ we get stuck on the unresolvable config. However, the UX would be consistent, and it seems like the better trade-off.
