### ISSUE TITLE
Please add Splunk distribution

### ISSUE THREAD

**Issue by atoulme** [dash0hq/otelbin#160]
Hello and thank you! I am looking to add the Splunk distribution to supported distributions.

**Comment by mmanciop** [comment]
Hi @atoulme, in #167 I took a stab at explaining the necessary steps. Care to give it a try? :-)

**Comment by atoulme** [comment]
Thanks, will get on it soon.

**Comment by atoulme** [comment]
Please assign the issue to me :)

**Comment by joschi** [comment]
Closed via https://github.com/dash0hq/otelbin/pull/343. Thanks for your contribution! ❤️
