### ISSUE TITLE
Support export/download of visualization as image

### ISSUE THREAD

**Issue by bripkens** [dash0hq/otelbin#168]
# Why

https://cloud-native.slack.com/archives/C01N6P7KR6W/p1698944576265539?thread_ts=1698853889.703259&cid=C01N6P7KR6W

# What

https://reactflow.dev/examples/misc/download-image

**Comment by samueljrz** [comment]
I would like to develop and contribute to this feature if possible. Can I assign it to me?

**Comment by bripkens** [comment]
Hey @samueljrz,

if you are interested in contributing this, feel free to give it a shot! I suppose a fitting location for the download button could be here:

<img width="235" alt="image" src="https://github.com/dash0hq/otelbin/assets/596443/7bccafdc-10d6-4b10-a5b1-39e2175071ea">

You can find the buttons withins this file: https://github.com/dash0hq/otelbin/blob/33c7e4b8b1880d3228a4ce0d1088e684a5dcd068/packages/otelbin/src/components/react-flow/ReactFlow.tsx#L237-L280

**Comment by samueljrz** [comment]
I thought to put it on the share section also would be a nice fit. So I did it both ways, so I could show it and get a second opinion. Just design part, tomorrow I'll write the logic part.

<img width="401" alt="Screenshot 2023-11-14 at 00 03 15" src="https://github.com/dash0hq/otelbin/assets/37130241/0f37e2e5-5aba-4356-98eb-dfbd577ec655">
<img width="401" alt="Screenshot 2023-11-14 at 00 04 14" src="https://github.com/dash0hq/otelbin/assets/37130241/01630cb7-19d6-498b-81db-94eeba6cbc75">

**Comment by bripkens** [comment]
@samueljrz: Good suggestion, let's put it under share as you proposed! 👍

**Comment by samueljrz** [comment]
I managed to raise the [PR](https://github.com/dash0hq/otelbin/pull/197), but I saw that there were some nuances to resolve. Tomorrow I will try to write some test. Please feel free to comment there and improve.

**Comment by samueljrz** [comment]
I had some issues configuring the tests to understand `ts` and `tsx`, as the testEnvironment of one is `ts-node` and the other is `jsdom` to be able to render components under test. I'm looking for a way to solve it, is this a block?

All other nuances were solved.

**Comment by bripkens** [comment]
Nope, not a blocker @samueljrz 👍. Cool that you are contributing ❤️ !

**Comment by samueljrz** [comment]
By the way, great project, I saw it as a great tool for the Open Telemetry community. It's already helping me a lot and I think I have a lot of resources to have hahaha.

**Comment by bripkens** [comment]
Fixed by @samueljrz!

**Comment by roshan-gh** [comment]
@samueljrz Great job. Thank you for your contribution ❤️
