### ISSUE TITLE
What are the prerequisites / requirements for adding new distro?

### ISSUE THREAD

**Issue by yurishkuro** [dash0hq/otelbin#179]
Jaeger is working on v2 that will be based on OTEL collector infrastructure, so we could point to this tool for config validation. I have a couple questions:
  1. what are the prerequisites that a disto must meet to be compatible with this tool?
  2. I assume extensions are also validated - are there plans for visualizing them (including inter-dependencies that will be supported in the next collector version)?

**Comment by mmanciop** [comment]
Hi @yurishkuro

1. the process to add a new distro is documented [here](https://github.com/dash0hq/otelbin/tree/main/packages/otelbin-validation). Pretty much is (1) you have RPMs for it (but the limitation can be lifted with some work) and (2) some bespoke logic is written for the [validation handler](https://github.com/dash0hq/otelbin/tree/main/packages/otelbin-validation/src).

2. A [suite of tests](https://github.com/dash0hq/otelbin/blob/main/packages/otelbin-validation/test/main.test.ts) is run to validate that our backend validation can detect correctness of some configurations (the backend needs to provide a uniform interface to the frontend).

Indeed everything is validated with the backend validation: it literally brings up that Distro's collector running on a Lambda function and tests the config that way.

**Comment by mmanciop** [comment]
@yurishkuro about:

> [extension] inter-dependencies that will be supported in the next collector version

I guess you mean the [start order](https://github.com/open-telemetry/opentelemetry-collector/issues/8732). If not, do you have some useful links on the topic?

**Comment by yurishkuro** [comment]
Yes, the start order. Although it's not accessible from the config only, so will be difficult to take into account here.

**Comment by mmanciop** [comment]
> Yes, the start order. Although it's not accessible from the config only, so will be difficult to take into account here.

@yurishkuro if I read the Collector's [extension lifecycle order](https://github.com/open-telemetry/opentelemetry-collector/pull/8768) PR right, there is no way to know statically whether the value of a configuration entry for a given extension references by ID another extension. Dangling extension references will be found with the backend validation, and we'll need to probably parse and contextualise in the editor:
1. The error message for dangling extension references
2. The error message for circular dependencies between extensions

CC @bripkens and @roshan-gh

**Comment by mmanciop** [comment]
@yurishkuro I am going ahead and closing the issue. Feel free to reopen if there is something that has not been addressed yet.
