### ISSUE TITLE
Monaco not loading with Pi-Hole Common Setup

### ISSUE THREAD

**Issue by DennisRippinger** [dash0hq/otelbin#223]
At home, I run a PI-Hole Setup using the Block List from https://github.com/StevenBlack/hosts, which lists `cdn.jsdelivr.net`. It may or may not be sensible from the Block List, but I thought you should know this. 

Otherwise, the page remains loading:

![image](https://github.com/dash0hq/otelbin/assets/1452505/4bffbc76-612f-4eda-811e-5ad0544f34c7)

**Comment by bripkens** [comment]
Hey @DennisRippinger,

thank you for calling this out.

It seems like this should resolve itself, as the `hosts` team has revisited their decision to block jsdelivr.net. See https://github.com/StevenBlack/hosts/issues/2518#issuecomment-1829683046
