### ISSUE TITLE
www.otelbin.io Editor does not work

### ISSUE THREAD

**Issue by lucarota** [dash0hq/otelbin#298]
Hi all,

I'm trying to use https://www.otelbin.io/ but the editor doesn't work.
The site can't load clerk bowrser dependency. Here the error:
![image](https://github.com/dash0hq/otelbin/assets/7235722/d3da5497-378c-4de0-bb08-c915b9a75454)

Thank you,
Luca

**Comment by marcelbirkner** [comment]
Hi @lucarota 

I just tried it myself and it is working fine. Also login via Clerk works. Which browser (version) are you using. Did you try incognito mode or clearing browser cache?

<img width="1911" alt="image" src="https://github.com/dash0hq/otelbin/assets/558256/61c9d63b-f53e-4c41-9531-10387d0b2dc8">

**Comment by lucarota** [comment]
oh I just tried from a consumer network and it works.
My corporate firewall is blocking the request.
Sorry for the inconvenience.

Thank you
