### ISSUE TITLE
Connector visualization issue

### ISSUE THREAD

**Issue by jangaraj** [dash0hq/otelbin#313]
I have [OTEL config](https://www.otelbin.io/?#config=connectors%3A*N__routing%2Flogs%3A*N____default*_pipelines%3A*N____-_logs%2Fout-drop*N____error*_mode%3A_ignore*N____table%3A*N____-_pipelines%3A*N______-_logs%2Fout-bbb*N______statement%3A_route*C*D_where_attributes%5B%22attribute%22%5D_*E*E_%22bbb%22*N____-_pipelines%3A*N______-_logs%2Fout-aaa*N______statement%3A_route*C*D_where_attributes%5B%22attribute%22%5D_*E*E_%22aaa%22*N____-_pipelines%3A*N______-_logs%2Fout-ccc*N______statement%3A_route*C*D_where_attributes%5B%22attribute%22%5D_*E*E_%22ccc%22*N____-_pipelines%3A*N______-_logs%2Fout-ddd*N______statement%3A_route*C*D_where_attributes%5B%22attribute%22%5D_*E*E_%22ddd%22*N____-_pipelines%3A*N______-_logs%2Fout-eee*N______statement%3A_route*C*D_where_attributes%5B%22attribute%22%5D_*E*E_%22eee%22*Nexporters%3A*N__debug%3A_%7B%7D*N__debug%2Fbbb%3A*N____verbosity%3A_detailed*N__debug%2Fdetailed%3A*N____verbosity%3A_detailed*N__debug%2Fdrop%3A*N____verbosity%3A_detailed*N__debug%2Faaa%3A*N____verbosity%3A_detailed*N__debug%2Fccc%3A*N____verbosity%3A_detailed*N__debug%2Fddd%3A*N____verbosity%3A_detailed*N__debug%2Feee%3A*N____verbosity%3A_detailed*N__logging%3A_null*N__otlphttp%2Fgrafana-cloud-bbb%3A*N____auth%3A*N______authenticator%3A_basicauth%2Fgrafana-cloud-bbb*N____endpoint%3A_https%3A%2F%2Fotlp-gateway-prod-us-central-0.grafana.net%2Fotlp*N____retry*_on*_failure%3A*N______enabled%3A_true*N______initial*_interval%3A_3s*N______max*_interval%3A_300s*N__otlphttp%2Fgrafana-cloud-aaa%3A*N____auth%3A*N______authenticator%3A_basicauth%2Fgrafana-cloud-aaa*N____endpoint%3A_https%3A%2F%2Fotlp-gateway-prod-us-central-0.grafana.net%2Fotlp*N____retry*_on*_failure%3A*N______enabled%3A_true*N______initial*_interval%3A_3s*N______max*_interval%3A_300s*N__otlphttp%2Fgrafana-cloud-ccc%3A*N____auth%3A*N______authenticator%3A_basicauth%2Fgrafana-cloud-ccc*N____endpoint%3A_https%3A%2F%2Fotlp-gateway-prod-us-central-0.grafana.net%2Fotlp*N____retry*_on*_failure%3A*N______enabled%3A_true*N______initial*_interval%3A_3s*N______max*_interval%3A_300s*N__otlphttp%2Fgrafana-cloud-ddd%3A*N____auth%3A*N______authenticator%3A_basicauth%2Fgrafana-cloud-ddd*N____endpoint%3A_https%3A%2F%2Fotlp-gateway-prod-us-central-0.grafana.net%2Fotlp*N____retry*_on*_failure%3A*N______enabled%3A_true*N______initial*_interval%3A_3s*N______max*_interval%3A_300s*N__otlphttp%2Fgrafana-cloud-eee%3A*N____auth%3A*N______authenticator%3A_basicauth%2Fgrafana-cloud-eee*N____endpoint%3A_https%3A%2F%2Fotlp-gateway-prod-us-central-0.grafana.net%2Fotlp*N____retry*_on*_failure%3A*N______enabled%3A_true*N______initial*_interval%3A_3s*N______max*_interval%3A_300s*Nextensions%3A*N__basicauth%2Fgrafana-cloud-bbb%3A*N____client*_auth%3A*N______password%3A_TODO*N______username%3A_TODO*N__basicauth%2Fgrafana-cloud-aaa%3A*N____client*_auth%3A*N______password%3A_TODO*N______username%3A_TODO*N__basicauth%2Fgrafana-cloud-ccc%3A*N____client*_auth%3A*N______password%3A_TODO*N______username%3A_TODO*N__basicauth%2Fgrafana-cloud-ddd%3A*N____client*_auth%3A*N______password%3A_TODO*N______username%3A_TODO*N__basicauth%2Fgrafana-cloud-eee%3A*N____client*_auth%3A*N______password%3A_TODO*N______username%3A_TODO*N__basicauth%2Fserver%3A*N____htpasswd%3A*N______inline%3A_%7C*N________user%3Apass*N__health*_check%3A*N____check*_collector*_pipeline%3A*N______enabled%3A_false*N____endpoint%3A_0.0.0.0%3A13133*Nprocessors%3A*N__batch%3A_%7B%7D*N__memory*_limiter%3A*N____check*_interval%3A_5s*N____limit*_percentage%3A_80*N____spike*_limit*_percentage%3A_25*Nreceivers%3A*N__otlp%3A*N____protocols%3A*N______grpc%3A*N________auth%3A*N__________authenticator%3A_basicauth%2Fserver*N________endpoint%3A_0.0.0.0%3A4317*N______http%3A*N________auth%3A*N__________authenticator%3A_basicauth%2Fserver*N________endpoint%3A_0.0.0.0%3A4318*N__prometheus%3A*N____config%3A*N______scrape*_configs%3A*N______-_job*_name%3A_opentelemetry-central-collector*N________scrape*_interval%3A_10s*N________static*_configs%3A*N________-_labels%3A*N____________application%3A_opentelemetry-central-collector*N__________targets%3A*N__________-_0.0.0.0%3A8888*Nservice%3A*N__extensions%3A*N__-_health*_check*N__-_basicauth%2Fgrafana-cloud-aaa*N__-_basicauth%2Fserver*N__pipelines%3A*N____logs%2Fin%3A*N______exporters%3A*N______-_routing%2Flogs*N______processors%3A*N______-_memory*_limiter*N______-_batch*N______receivers%3A*N______-_otlp*N____logs%2Fout-bbb%3A*N______exporters%3A*N______-_debug%2Fbbb*N______processors%3A*N______-_memory*_limiter*N______-_batch*N______receivers%3A*N______-_routing%2Flogs*N____logs%2Fout-drop%3A*N______exporters%3A*N______-_debug%2Fdrop*N______processors%3A*N______-_memory*_limiter*N______-_batch*N______receivers%3A*N______-_routing%2Flogs*N____logs%2Fout-aaa%3A*N______exporters%3A*N______-_debug%2Faaa*N______processors%3A*N______-_memory*_limiter*N______-_batch*N______receivers%3A*N______-_routing%2Flogs*N____logs%2Fout-ccc%3A*N______exporters%3A*N______-_debug%2Fccc*N______processors%3A*N______-_memory*_limiter*N______-_batch*N______receivers%3A*N______-_routing%2Flogs*N____logs%2Fout-ddd%3A*N______exporters%3A*N______-_debug%2Fddd*N______processors%3A*N______-_memory*_limiter*N______-_batch*N______receivers%3A*N______-_routing%2Flogs*N____logs%2Fout-eee%3A*N______exporters%3A*N______-_debug%2Feee*N______processors%3A*N______-_memory*_limiter*N______-_batch*N______receivers%3A*N______-_routing%2Flogs*N____metrics%3A*N______exporters%3A*N______-_otlphttp%2Fgrafana-cloud-aaa*N______processors%3A*N______-_memory*_limiter*N______-_batch*N______receivers%3A*N______-_prometheus*N______-_otlp*N__telemetry%3A*N____logs%3A*N______encoding%3A_json*N______level%3A_info*N____metrics%3A*N______address%3A_0.0.0.0%3A8888*N%7E&distro=otelcol-contrib%7E&distroVersion=v0.97.0%7E), where one pipeline `logs/in` with routing connector routes logs based on attribute to different pipelines `logs/out-X`. It looks like current version doesn't visualize/connect these pipelines correctly:

![image](https://github.com/dash0hq/otelbin/assets/1182932/254e1813-e0b5-4918-af9d-452a61dfa838)

Thank you for your good job.

**Comment by mmanciop** [comment]
Hi @jangaraj , thanks for the bug report!
